WEB10/hw_quotes/hw_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

WEB10/hw_quotes/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="root_paginate"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("add_author/", views.add_author, name="add_author"),
    path("add_tag/", views.add_tag, name="add_tag"),
    path("show_author/<int:author_id>", views.show_author, name="show_author"),
    path("viewing_tag/<str:tag_name>", views.viewing_tag, name="viewing_tag"),

]

WEB10/hw_quotes/users/urls.py
from django.urls import path

from . import views

from django.contrib.auth.views import LogoutView   #LoginView,

from .forms import LoginForm
from .views import RegisterView#, LoginView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),

    path('signin/', views.signin, name='signin'),

    path('logout/', views.logoutuser, name='logoutuser'),
]

WEB10/hw_quotes/quotes/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

WEB10/hw_quotes/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple, Select, \
    ModelChoiceField
from .models import Quote, Tag, Author


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput())  # blank=True,
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), required=True, widget=SelectMultiple())  # blank=True,
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=Select())



    class Meta:
        model = Quote
        fields = ("quote", "author", "tags")

class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50, required=True, widget=TextInput())
    born_location = CharField(max_length=150, required=True, widget=TextInput())
    bio = CharField(required=True, widget=TextInput())


    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "bio")


class TagForm(ModelForm):
    name = CharField(min_length=2, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]



WEB10/hw_quotes/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .models import Quote, Author, Tag
from .forms import QuoteForm, AuthorForm, TagForm

from django.contrib.auth.decorators import login_required


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={"quotes": quotes_on_page})


def show_author(request, author_id):
    author = Author.objects.get(pk=author_id)

    return render(request, 'quotes/show_author.html', context={"author": author})


def viewing_tag(request, tag_name, page=1):
    print(tag_name)
    tag_obj = Tag.objects.get(name=tag_name)
    print(tag_obj, type(tag_obj))
    quotes = Quote.objects.filter(tags=tag_obj)
    return render(request, 'quotes/viewing_tag.html', context={"quotes": quotes})


@login_required
def add_quote(request):
    print(" start add quote   ")
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():

            print("  form valid ")

            form.save()
            print("  save new quote ")
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/add_quote.html', {'form': form})

    return render(request, 'quotes/add_quote.html', {'form': QuoteForm()})



@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/add_tag.html', {'form': form})

    return render(request, 'quotes/add_tag.html', {'form': TagForm()})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/add_author.html', {'form': form})

    return render(request, 'quotes/add_author.html', {'form': AuthorForm()})

WEB10/hw_quotes/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div>
        <label>Enter Author`s fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
        <div>
        <label>Enter Author`s born_date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
        <div>
        <label>Enter Author`s born_location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
        <div>
        <label>Enter Author`s biography:
            {{ form.bio }}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Add Quote</h2>
</div>

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div>
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <br>
    <div>
        <label> Select tags:

            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <br>
    <div>
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <br>
    <br>

    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/add_quote_without_author.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Add Quote</h2>
</div>

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div>

        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <br>
    <div>
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <br>
    <div>
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <br>
    <br>

    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    <div>
        <label>Enter the tag name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href=" {% static 'quotes/style.css' %} ">

    <title>Homework 10 - WEB - Python 10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-7">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-5">
                <p>

                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logoutuser' %}" class="btn btn-primary">Logout</a>
                    <a href="{% url 'quotes:add_tag' %}" class="btn btn-info">Add Tag</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-info">Add Author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-info">Add Quote</a>

                    {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:signin' %}" class="btn btn-primary">  SignIn  </a>

                    {% endif %}

                </p>
            </div>
        </div>



    {% block content %} {% endblock %}



    </div>
</body>
</html>

WEB10/hw_quotes/quotes/templates/quotes/base_with_if.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href=" {% static 'quotes/style.css' %} ">

    <title>Homework 10 - WEB - Python 10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="#" class="btn btn-primary">Login</a>
                    <a href="#" class="btn btn-primary">Logout</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>

                </p>
            </div>
        </div>



    {% block content %} {% endblock %}



    </div>
</body>
</html>




WEB10/hw_quotes/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/show_author/{{quote.author.id}}">(about)</a>
        </span>
            <div class="tags">
                Tags:

                {% for tag in quote.tags.all %}
                <a class="tag" href="/viewing_tag/{{ tag.name }}">{{tag.name}}</a>
                {% endfor %}


            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/show_author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">

    <h1>{{author.fullname}}</h1>
    <p>born_date: <b>{{author.born_date}}</b></p>
    <p>born_location: <b>{{author.born_location}}</b></p>
    <p>Description: <b>{{author.bio}}</b></p>


</div>

{% endblock %}

WEB10/hw_quotes/quotes/templates/quotes/viewing_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/show_author/{{quote.author.id}}">(about)</a>
        </span>
            <div class="tags">
                Tags:

                {% for tag in quote.tags.all %}
                <a class="tag" href="/viewing_tag/{{ tag.name }}">{{tag.name}}</a>
                {% endfor %}


            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}